{
  "before_script": [
    "echo \"no tests\""
  ], 
  "install": [
    "echo \"nothing needs to be installed\""
  ], 
  "language": "node_js", 
  "script": [
    "docker --version", 
    "docker build -t reverseproxy ./project/udagram-reverseproxy", 
    "docker tag reverseproxy dockerrajulapati/reverseproxy:latest", 
    "docker build -t udagram-api-user ./project/udagram-api-user", 
    "docker tag udagram-api-user dockerrajulapati/udagram-api-user:latest", 
    "docker build -t udagram-api-feed ./project/udagram-api-feed", 
    "docker tag udagram-api-feed dockerrajulapati/udagram-api-feed:latest", 
    "docker build -t udagram-frontend ./project/udagram-frontend", 
    "docker tag udagram-frontend dockerrajulapati/udagram-frontend:latest"
  ], 
  "services": [
    "docker"
  ], 
  "after_success": [
    "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin", 
    "docker push dockerrajulapati/reverseproxy", 
    "docker push dockerrajulapati/udagram-api-user", 
    "docker push dockerrajulapati/udagram-api-feed", 
    "docker push dockerrajulapati/udagram-frontend"
  ], 
  "node_js": [
    13
  ]
}