apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: dockerrajulapati/udagram-frontend:v1
        env:
        - name: POSTGRES_USERNAME
          value: tau_db_user1
        - name: POSTGRES_PASSWORD
          value: Taudb!0001
        - name: aws_access_key_id
          value: QUtJQVhMV0RZQ0Y0UUNTMzVFUkY=
        - name: aws_secret_access_key
          value: cDZISUpuTVg2alRrdzNBOFZvd0pEU3JPak1md2dJbUtmMWRNM2NudAo=
        - name: POSTGRES_HOST
          value: tau-poc-db.cvajooc0iqsc.us-east-2.rds.amazonaws.com
        - name: POSTGRES_DB
          value: postgres
        - name: AWS_BUCKET
          value: arn:aws:s3:::mymicrobucket
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_PROFILE
          value: default
        - name: JWT_TOKENT
          value: testing
        - name: URL
          value: http://localhost:8100

        ports:
        - containerPort: 80